-- Royal Golf Club — Phase 1 EMERGENCY ROLLBACK
-- Restores every table from phase1_backup. Anything saved AFTER the migration is lost,
-- so use this only shortly after go-live, and redeploy the previous app version
-- (git revert of the Phase 1 app commits) straight after running it.
BEGIN;
DO $$ DECLARE c record; t text; BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'phase1_backup') THEN
    RAISE EXCEPTION 'No phase1_backup schema — nothing to roll back to.';
  END IF;
  FOR c IN SELECT conrelid::regclass::text AS tbl, conname FROM pg_constraint WHERE contype = 'f' AND conname LIKE 'fk\_%' LOOP
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', c.tbl, c.conname);
  END LOOP;
  FOREACH t IN ARRAY ARRAY['players','rounds','fine_types','fines','fine_payments','saturday_events',
    'saturday_signups','gps_shots','tournaments','tournament_players','tournament_matches','tournament_scores'] LOOP
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id DROP IDENTITY IF EXISTS', t);
    EXECUTE format('DELETE FROM public.%I', t);
  END LOOP;
  ALTER TABLE public.players DROP COLUMN archived_at, DROP COLUMN legacy_id;
  FOREACH t IN ARRAY ARRAY['players','rounds','fine_types','fines','fine_payments','saturday_events',
    'saturday_signups','gps_shots','tournaments','tournament_players','tournament_matches','tournament_scores'] LOOP
    EXECUTE format('INSERT INTO public.%I SELECT * FROM phase1_backup.%I', t, t);
  END LOOP;
  -- gps_shots always had database ids; give it back an identity after its highest id.
  ALTER TABLE public.gps_shots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval(pg_get_serial_sequence('public.gps_shots', 'id'), greatest((SELECT coalesce(max(id), 0) FROM public.gps_shots), 1),
                 (SELECT count(*) > 0 FROM public.gps_shots));
  FOR c IN SELECT * FROM phase1_backup.dropped_fks LOOP
    EXECUTE format('ALTER TABLE %s ADD CONSTRAINT %I %s', c.tbl, c.conname, c.def);
  END LOOP;
END $$;
-- Phase 0 login (without the archived check — the column is gone).
CREATE OR REPLACE FUNCTION public.login(p_email text, p_pin text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
DECLARE pl public.players%ROWTYPE; res text;
BEGIN
  SELECT * INTO pl FROM public.players WHERE lower(email) = lower(trim(p_email)) LIMIT 1;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok', false); END IF;
  res := public._check_pin(pl.id, p_pin);
  IF res = 'unset' THEN RETURN jsonb_build_object('ok', true, 'id', pl.id, 'name', pl.name, 'needs_pin', true); END IF;
  IF res = 'ok'    THEN RETURN jsonb_build_object('ok', true, 'id', pl.id, 'name', pl.name); END IF;
  RETURN jsonb_build_object('ok', false, 'locked', res = 'locked');
END $fn$;
-- The restored app is the old one, which sends no version header: switch the gate off.
ALTER ROLE authenticator RESET pgrst.db_pre_request;
NOTIFY pgrst, 'reload schema';
NOTIFY pgrst, 'reload config';
COMMIT;
