-- Production-shaped schema for the PGlite testbed (as observed through the API on 2026-09-24).
-- gps_shots already had database-assigned ids. The rehearsal on the real database is the
-- final word: if it disagrees with this file, fix this file to match production.
CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE authenticator; CREATE ROLE service_role;
CREATE TABLE public.players (id bigint PRIMARY KEY, name text, color int, handicap numeric, hcp_history jsonb,
  created_at timestamptz DEFAULT now(), is_admin boolean DEFAULT false, approved boolean DEFAULT true, pin text,
  email text, is_social boolean DEFAULT false, bag jsonb, dgu_number text);
CREATE TABLE public.rounds (id bigint PRIMARY KEY, player_id bigint NOT NULL, course text, date text, tee_id text,
  tee_name text, tee_color text, rating numeric, slope int, hcp_index numeric, course_hcp int, playing_hcp int,
  notes text, holes jsonb, created_at timestamptz DEFAULT now(), tee_time text, marker_id bigint, marker_holes jsonb);
CREATE TABLE public.fine_types (id bigint PRIMARY KEY, name text, amount numeric, created_at timestamptz DEFAULT now(), active boolean DEFAULT true);
CREATE TABLE public.fines (id bigint PRIMARY KEY, player_id bigint NOT NULL, fine_type_id bigint, round_id bigint, hole int,
  date text, issued_by bigint NOT NULL, notes text, created_at timestamptz DEFAULT now(), amount numeric);
CREATE TABLE public.fine_payments (id bigint PRIMARY KEY, player_id bigint NOT NULL, amount numeric, date text, note text,
  recorded_by bigint NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE public.saturday_events (id bigint PRIMARY KEY, date text, locked boolean, tee_times jsonb, created_at timestamptz DEFAULT now(), cancelled boolean);
CREATE TABLE public.saturday_signups (id bigint PRIMARY KEY, player_id bigint NOT NULL, date text, tee_time text, group_num int,
  created_at timestamptz DEFAULT now(), early_tee_request boolean, early_tee_reason text);
CREATE TABLE public.gps_shots (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, player_id bigint NOT NULL, round_date text,
  hole int, shot_num int, type text, lat double precision, lng double precision, club text, shot_weight text, wind_speed numeric,
  wind_dir text, wind_deg numeric, result text, recorded_at timestamptz, lie text, direction text, shot_outcome text, accuracy_m numeric);
CREATE TABLE public.tournaments (id bigint PRIMARY KEY, name text, date text, tee_id text, status text, team_a_name text,
  team_b_name text, team_a_captain_id bigint, team_b_captain_id bigint, created_at timestamptz DEFAULT now());
CREATE TABLE public.tournament_players (id bigint PRIMARY KEY, tournament_id bigint, player_id bigint, team text);
CREATE TABLE public.tournament_matches (id bigint PRIMARY KEY, tournament_id bigint, round int, match_num int, status text,
  tee_id text, result jsonb, team_a_p1_id bigint, team_a_p2_id bigint, team_b_p1_id bigint, team_b_p2_id bigint);
CREATE TABLE public.tournament_scores (id bigint PRIMARY KEY, match_id bigint, hole int, player_id bigint, gross int);
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon, authenticated;
